services:
  ml-client:
    build:
      context: ./ml-client
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - my-network

  ml-server:
    build:
      context: ./ml-server
    ports:
      - 8001:8001
    networks:
      - my-network

networks:
  my-network: